const defaults=[
 {id:'weather',title:'Weather',label:'TODAY IN YOUR CITY',size:'medium',html:'<div class="weather-art">☼</div><div class="temperature">72°</div><div class="weather-meta">Sunny · Feels like 74°</div>'},
 {id:'date',title:'Wednesday',label:'SEPTEMBER 16, 2026',size:'small',html:'<div class="date-number">16</div><div class="date-meta">September · Week 38</div>'},
 {id:'tasks',title:'Today\'s focus',label:'3 THINGS TO DO',size:'medium',html:'<div class="task-line done"><i class="check"></i>Reply to emails</div><div class="task-line"><i class="check"></i>Finish project brief</div><div class="task-line"><i class="check"></i>Take a proper break</div>'},
 {id:'quote',title:'A thought for today',label:'THE DAILY NOTE',size:'wide',html:'<blockquote>“The best way out is always through.”</blockquote><cite>— Robert Frost</cite>'},
 {id:'clock',title:'Local time',label:'NEW YORK · EST',size:'small',html:'<div class="clock-time" id="clock-time">10:42 <small>AM</small></div>'},
 {id:'notes',title:'The Notepad',label:'LAST EDITED 2 MIN AGO',size:'wide',html:'<p>There is something special about beginning again.</p><a href="#notepad">Open The Notepad →</a>'}
];
const extras=[['calendar','Calendar','YOUR WEEK AT A GLANCE'],['pomodoro','Focus timer','MAKE TIME FOR DEEP WORK'],['bookmarks','Bookmarks','SAVED FOR LATER'],['music','Now playing','A LITTLE BACKGROUND MUSIC'],['habits','Habit tracker','SMALL STEPS, EVERY DAY'],['finance','Spending','THIS MONTH SO FAR'],['weather2','Air quality','TODAY OUTSIDE'],['links','Quick links','YOUR FAVORITES'],['journal','Journal prompt','A QUESTION TO CONSIDER'],['mail','Inbox zero','YOU\'RE ALL CAUGHT UP'],['plants','Plant care','DON\'T FORGET TO WATER'],['affirmation','Affirmation','A KIND WORD TO YOURSELF'],['world','World clock','SOMEWHERE ELSE'],['reading','Reading list','THINGS TO EXPLORE']];
let widgets=JSON.parse(localStorage.getItem('widget-space-widgets')||'null')||defaults.slice(0,5);let notes=JSON.parse(localStorage.getItem('widget-space-notes')||'null')||[{title:'A fresh start',date:'Today'}];
const dashboard=document.querySelector('#dashboard');
function renderWidgets(){dashboard.innerHTML='';widgets.forEach((w,i)=>{const el=document.createElement('article');el.className='widget '+w.id;el.dataset.size=w.size||'small';el.draggable=true;el.dataset.index=i;el.innerHTML=`<div class="widget-top"><div><span class="widget-label">${w.label}</span><h3>${w.title}</h3></div><button class="more">···</button></div>${w.html}`;dashboard.appendChild(el)});updateClock();}
function saveWidgets(){localStorage.setItem('widget-space-widgets',JSON.stringify(widgets))}function updateClock(){const c=document.querySelector('#clock-time');if(c){const d=new Date();c.innerHTML=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})+' <small>'+d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',hour12:true}).slice(-2)+'</small>'}}
renderWidgets();setInterval(updateClock,30000);
dashboard.addEventListener('dragstart',e=>{if(e.target.closest('.widget'))e.dataTransfer.setData('index',e.target.closest('.widget').dataset.index)});dashboard.addEventListener('dragover',e=>e.preventDefault());dashboard.addEventListener('drop',e=>{const target=e.target.closest('.widget');if(!target)return;const from=+e.dataTransfer.getData('index'),to=+target.dataset.index;[widgets[from],widgets[to]]=[widgets[to],widgets[from]];saveWidgets();renderWidgets()});
function navigate(){const page=location.hash.slice(1)||'home';document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));document.querySelector(`#${page}-page`)?.classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(a=>a.classList.toggle('active',a.dataset.page===page));document.querySelector('#page-label').textContent=page==='notepad'?'The Notepad':page[0].toUpperCase()+page.slice(1)}window.addEventListener('hashchange',navigate);navigate();
const modal=document.querySelector('#widget-modal');function openModal(){const lib=document.querySelector('#widget-library');lib.innerHTML=extras.map((x,i)=>`<button class="library-item" data-extra="${i}"><strong>${x[1]}</strong><small>${x[2]}</small></button>`).join('');modal.classList.remove('hidden')}document.querySelector('#add-widget').onclick=openModal;document.querySelector('#browse-widgets').onclick=openModal;document.querySelector('#close-modal').onclick=()=>modal.classList.add('hidden');document.querySelector('#widget-library').onclick=e=>{const b=e.target.closest('[data-extra]');if(!b)return;const x=extras[+b.dataset.extra];widgets.push({id:x[0],title:x[1],label:x[2],size:'small',html:'<p style="margin-top:25px;color:#999">Your '+x[1].toLowerCase()+' will appear here.</p>'});saveWidgets();renderWidgets();modal.classList.add('hidden')};
function renderNotes(){document.querySelector('#notes-list').innerHTML=notes.map(n=>`<div class="note-list-item"><strong>${n.title}</strong><small>${n.date}</small></div>`).join('');document.querySelector('#note-count').textContent=notes.length}renderNotes();const editor=document.querySelector('#editor'),title=document.querySelector('#note-title');function saveNote(){notes[0]={title:title.value||'Untitled note',date:'Just now'};localStorage.setItem('widget-space-notes',JSON.stringify(notes));renderNotes();document.querySelector('#save-status').textContent='Saved just now'}editor.addEventListener('input',()=>{document.querySelector('#word-count').textContent=(editor.innerText.trim().split(/\s+/).filter(Boolean).length)+' words';saveNote()});title.addEventListener('input',saveNote);document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{document.execCommand(b.dataset.command,false,b.dataset.value||null);editor.focus()});document.querySelector('#new-note').onclick=()=>{title.value='Untitled note';editor.innerHTML='<p>Start writing here...</p>';saveNote();editor.focus()};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='s'){e.preventDefault();saveNote()}});
document.querySelector('#theme-select').onchange=e=>{document.body.dataset.theme=e.target.value;localStorage.setItem('widget-space-theme',e.target.value)};document.querySelector('#compact-toggle').onchange=e=>document.body.classList.toggle('compact',e.target.checked);document.querySelector('#reset-widgets').onclick=()=>{widgets=defaults.slice(0,5);saveWidgets();renderWidgets()};document.querySelector('#focus-mode').onclick=()=>document.body.classList.toggle('focus-mode');
